### ISSUE TITLE
"pdf" links should directly download the pdf, not link to github repo

### ISSUE THREAD

**Issue by mb706** [compstat-lmu/lecture_i2ml#369]
I'm talking about this page https://compstat-lmu.github.io/lecture_i2ml/articles/content.html
where I click on a "pdf" link. If this is not the official site you can disregard this.

Maybe you can get direct pdf download links if you link to `https://compstat-lmu.github.io/..../x.pdf`

**Comment by berndbischl** [comment]
i am sure what the issue is? is anything inconvenient?
the github io page is the "official" entry point (for readers, students and so on)
the normal github repo for authors / developers.

the pdfs are created by makefiles in the normal repo then pushed to it.
then we link to them in the pages.
but again: whats bothering you?

**Comment by berndbischl** [comment]
ok sorry, i get it now. because the pdf is not directly dled, but "opened" in the repo, i see

**Comment by berndbischl** [comment]
i dont know how to fix this to be honest. it doesnt seem like a super bad problem?

**Comment by berndbischl** [comment]
if you right-click on the pdf links and say "save to" it works as exepected an without going to the repo.

 maybe we should add a sentence that people should do that, and all is good?

**Comment by mb706** [comment]
Maybe deploy the pdfs to the `gh-pages` branch and link to them there?

**Comment by HeidiSeibold** [comment]
I figured out a way how to do this. Just use relative links. 

See https://github.com/compstat-lmu/lecture_i2ml/commit/46409126b16ec2f2ac7caf58ce41925b8a460f61
